### ISSUE TITLE
Use of deprecated and now removed Before() and After() router methods.

### ISSUE THREAD

**Issue by Shkeats** [andersao/laravel-request-logger#10]
The before and after methods used on the Laravel Router in LoggerServiceProvider on lines 38 and 42 have been deprecated since 5.0 and have been completely removed from Laravel 5.2 which prevents this package from being used.

**Comment by zorro786** [comment]
Any fixes on this?

**Comment by andersao** [comment]
A new version was released [1.2.0](https://github.com/andersao/laravel-request-logger/releases/tag/1.2.0). Check it out.
