### ISSUE TITLE
LogTask extends App\Jobs\Job, this won't exist in many cases.

### ISSUE THREAD

**Issue by Shkeats** [andersao/laravel-request-logger#11]
The LogTask extends App\Jobs\Job and therefore assumes the laravel application it is in use with has the namespace App and still contains the default job class. This won't always be the case as the namespace is editable and the job class deletable.

**Comment by andersao** [comment]
A new version was released [1.2.0](https://github.com/andersao/laravel-request-logger/releases/tag/1.2.0). Check it out.
