### ISSUE TITLE
Not compatible with 5.3?

### ISSUE THREAD

**Issue by itsazzad** [andersao/laravel-request-logger#15]
Not seems to be  compatible with Laravel 5.3?

**Comment by karmendra** [comment]
Saved my day. Thanks. Hope this gets merged in soon

**Comment by Daniesy** [comment]
Can you please merge this pull request?

**Comment by rutherang** [comment]
@andersao Could you kindly check if this changes is suited to your taste and be merge to your project to be compatible with Laravel 5.3 up

**Comment by andersao** [comment]
A new version was released [1.2.0](https://github.com/andersao/laravel-request-logger/releases/tag/1.2.0). Check it out.
